### ISSUE TITLE
The module "Goutte_pendante" failed to initialize 

### ISSUE THREAD

**Issue by jwarner123** [adaerr/pendent-drop#1]
Hi I'm getting the error The module "Goutte_penante" failed to initialize. What am I missing from the downloads?

**Comment by adaerr** [comment]
Hi, could you specify how you installed the plugin ? We use it with up-to-date Fiji installations, so unless something broke _very_ recently we can rule out bit-rotting ;-) Something must be wrong with your set-up.

Unless you know what you are doing, please 

1. use [ImageJ2 or Fiji](https://imagej.net/Downloads) and 

2. use its updater (Help->Update.., Manage update sites) to enable Goutte_pendante as described [here](http://imagej.net/Following_an_update_site).

And finally: please use the [ImageJ Forum](https://forum.image.sc/t/pendent-drop-plugin-how-to-use/290) to ask about installation and usage problems with this plugin. The github issue tracker is meant for bugs and programming issues. I'll leave this issue open for the moment, but in the future I shall close issues that should really be on the ImageJ Forum.
